"""empty message

Revision ID: 08026144804d
Revises: ad6fc45054ca
Create Date: 2026-05-20 06:29:41.676005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08026144804d'
down_revision: Union[str, Sequence[str], None] = 'ad6fc45054ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('ux_username', sa.String(), nullable=False),
    sa.Column('ux_pass', sa.String(), nullable=False),
    sa.Column('ux_url', sa.String(), nullable=False),
    sa.Column('out_url', sa.String(), nullable=False),
    sa.Column('out_cert', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('vpn_keys', sa.Column('nodes_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'vpn_keys', 'nodes', ['nodes_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vpn_keys', type_='foreignkey')
    op.drop_column('vpn_keys', 'nodes_id')
    op.drop_table('nodes')
    # ### end Alembic commands ###
