"""add_inbound_port_to_nodes

Revision ID: 16e12c16213c
Revises: 735d0c75d85a
Create Date: 2026-06-07 18:16:16.098829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16e12c16213c'
down_revision: Union[str, Sequence[str], None] = '735d0c75d85a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('inbound_port', sa.Integer(), server_default=sa.text('10000'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'inbound_port')
    # ### end Alembic commands ###
