"""empty message

Revision ID: 443ef3fe3f5d
Revises: 16e12c16213c
Create Date: 2026-06-16 09:40:17.778151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '443ef3fe3f5d'
down_revision: Union[str, Sequence[str], None] = '16e12c16213c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('reality_public_key', sa.String(), nullable=True))
    op.add_column('nodes', sa.Column('reality_short_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'reality_short_id')
    op.drop_column('nodes', 'reality_public_key')
    # ### end Alembic commands ###
