"""empty message

Revision ID: 5f5ba3eab159
Revises: 08026144804d
Create Date: 2026-05-21 03:34:07.711549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f5ba3eab159'
down_revision: Union[str, Sequence[str], None] = '08026144804d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('allow_new_key', sa.Boolean(), server_default=sa.text("'true'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'allow_new_key')
    # ### end Alembic commands ###
