"""empty message

Revision ID: 7d93b78595f2
Revises: 5f5ba3eab159
Create Date: 2026-05-21 03:55:19.813260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d93b78595f2'
down_revision: Union[str, Sequence[str], None] = '5f5ba3eab159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('vless_inbound', sa.Integer(), server_default=sa.text('1'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'vless_inbound')
    # ### end Alembic commands ###
