"""fix_is_active_default_and_billing_update

Revision ID: 9f911a000e50
Revises: ad6fc45054ca
Create Date: 2026-05-14 04:07:20.165475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f911a000e50'
down_revision: Union[str, Sequence[str], None] = 'ad6fc45054ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text("'true'"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('processed_payments')
    op.add_column('vpn_keys', sa.Column('nodes_id', sa.BigInteger(), server_default='1', nullable=False))
    op.create_foreign_key(None, 'vpn_keys', 'nodes', ['nodes_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vpn_keys', type_='foreignkey')
    op.drop_column('vpn_keys', 'nodes_id')
    op.create_table('processed_payments',
    sa.Column('invoice_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('invoice_id', name=op.f('processed_payments_pkey'))
    )
    op.drop_table('nodes')
    # ### end Alembic commands ###
